# Generated by Django 4.2.10 on 2024-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('main_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('main_category_name', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'Category_table',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('expiry_date', models.DateField()),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('main_category_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.category')),
            ],
            options={
                'db_table': 'product_table',
            },
        ),
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('seller_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('seller_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('experience', models.CharField(max_length=20, null=True)),
                ('license_number', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'seller_table',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=50, null=True)),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.category')),
            ],
            options={
                'db_table': 'Subcategory_table',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('sub_sub_category_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('sub_sub_category_name', models.CharField(max_length=50, null=True)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.subcategory')),
            ],
            options={
                'db_table': 'Sub2category_table',
            },
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('specification_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('specification_name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('expiry_date', models.DateField()),
                ('number_of_products', models.CharField(max_length=20, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
            ],
            options={
                'db_table': 'specification_table',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('image_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Sellerapp.product')),
            ],
            options={
                'db_table': 'product_image_table',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='seller_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.seller'),
        ),
    ]
