# Generated by Django 4.2.10 on 2024-02-29 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerapp', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
    ]
