# Generated by Django 4.2.10 on 2024-03-03 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerapp', '0004_alter_product_product_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand_table',
        ),
    ]
