# Generated by Django 4.2.10 on 2024-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sellerapp', '0001_initial'),
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=20, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('list_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'wishlist_table',
            },
        ),
        migrations.CreateModel(
            name='UserImage',
            fields=[
                ('image_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='images/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'user_image_table',
            },
        ),
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('house_id', models.AutoField(primary_key=True, serialize=False)),
                ('house_name', models.CharField(max_length=20, null=True)),
                ('house_number', models.CharField(max_length=20, null=True)),
                ('place', models.CharField(max_length=20, null=True)),
                ('post', models.CharField(max_length=20, null=True)),
                ('pin', models.CharField(max_length=20, null=True)),
                ('landmark', models.CharField(max_length=20, null=True)),
                ('city_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Adminapp.locationcity')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewRating',
            fields=[
                ('review_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('review', models.TextField()),
                ('rating', models.IntegerField(null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'review_rating_table',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(default=None, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'order_table',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('quantity', models.CharField(max_length=20, null=True)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'cart_table',
            },
        ),
    ]
