# Generated by Django 4.2.10 on 2024-03-03 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0005_alter_cart_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
