# Generated by Django 4.2.10 on 2024-03-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0007_usercart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='cart_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
