# Generated by Django 4.2.10 on 2024-03-13 12:43

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Sellerapp', '0005_alter_brand_table'),
        ('Userapp', '0010_alter_usercart_quantity_alter_wishlist_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentlyViewed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Sellerapp.product')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Userapp.user')),
            ],
            options={
                'db_table': 'recentlyviewed_table',
            },
        ),
    ]
