# Generated by Django 4.2.10 on 2024-03-16 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userapp', '0011_recentlyviewed'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table=None,
        ),
        migrations.AlterModelTable(
            name='recentlyviewed',
            table=None,
        ),
        migrations.AlterModelTable(
            name='reviewrating',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
        migrations.AlterModelTable(
            name='userimage',
            table=None,
        ),
        migrations.AlterModelTable(
            name='wishlist',
            table=None,
        ),
    ]
